language: node_js

node_js:
  - stable

install:
  - npm install

jobs:
  include:
    - stage: Build Library
      script: npm run build:lib
    - stage: Build Demo
      script: npm run build:demo
    - stage: Test
      script: npm run test

notifications:
  email: false
