language: node_js

node_js:
  - stable

install:
  - npm install

jobs:
  include:
    - stage: Build
      script: npm run build
    - stage: Test
      script: npm run test

notifications:
  email: false
