language: node_js

node_js:
  - stable

install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run build:lib
    - script: npm run build:demo
    - stage: test
      script: npm run test -s

cache:
  directories:
    - node_modules

notifications:
  email: false
