const PLAY_VIDEO = 'PLAY';
const PAUSE_VIDEO = 'PAUSE';
const MUTE_VIDEO = 'MUTE';
const UNMUTE_VIDEO = 'UNMUTE';
const MAXIMIZE_VIDEO = 'MAXIMIZE';
const MINIMIZE_VIDEO = 'MINIMIZE';

export {
  PLAY_VIDEO,
  PAUSE_VIDEO,
  MUTE_VIDEO,
  UNMUTE_VIDEO,
  MAXIMIZE_VIDEO,
  MINIMIZE_VIDEO
};
