const PLAY_VIDEO = 'PLAY';
const PAUSE_VIDEO = 'PAUSE';
const MUTE_VIDEO = 'MUTE';
const UNMUTE_VIDEO = 'UNMUTE';
const MAXIMIZE_VIDEO = 'MAXIMIZE';
const MINIMIZE_VIDEO = 'MINIMIZE';
const ADJUST_VOLUME = 'ADJUST_VOLUME';
const ADJUST_CURRENT_TIME = 'ADJUST_CURRENT_TIME';
const ADJUST_DURATION = 'ADJUST_DURATION';

export {
  PLAY_VIDEO,
  PAUSE_VIDEO,
  MUTE_VIDEO,
  UNMUTE_VIDEO,
  MAXIMIZE_VIDEO,
  MINIMIZE_VIDEO,
  ADJUST_VOLUME,
  ADJUST_CURRENT_TIME,
  ADJUST_DURATION
};
